# -- scene detection
scene_detection: pyscenedetect
scene_detection_conf:
  temp_dir: "./temp/"

# -- face detection
face_detection: dsfd
face_detection_conf:
  confidence_threshold: 0.35
  nms_iou_threshold: 0.5

# --face alignment
face_alignment:

# -- active speaker detection
active_speaker_detection: talknet
active_speaker_detection_conf:
  checkpoint_path: "./modules/active_speaker_detection/talknet_asd/weights/talknetasd_51frames_epoch4.pth"
  device: "cpu"

# -- automatic speech recognition
speech_recognition: whisper
speech_recognition_conf:
  model_size: "small"
  lang: "es"

pipeline: annotheia
pipeline_conf:
  min_length: 12
  threshold: 0.04
  window_size: 51
  smoothing_window_size: 11
  face_max_frame: 10
  min_face_size: 32
  max_face_distance_thr: 50
  method: "no_overlap+smoothing"
  save_scenes: false
