# -- scene detection
scene_detection: pyscenedetect
scene_detection_conf:
  temp_dir: "temp/"

# -- face detection
face_detection: retina
face_detection_conf:
  device: "cpu"
  threshold: 0.8
  model_id: "resnet50"

# --face alignment
face_alignment: fan
face_alignment_conf:
  device: "cpu"
  model_id: "2dfan2_alt"

# -- active speaker detection
active_speaker_detection: talknet
active_speaker_detection_conf:
  device: "cpu"
  checkpoint_path: "./modules/active_speaker_detection/talknet_asd/weights/english_talknetasd_ava_dataset.pth"

# -- automatic speech recognition
automatic_speech_recognition: whisper
automatic_speech_recognition_conf:
  model_size: "small"
  lang: "en"

pipeline: annotheia
pipeline_conf:
  min_length: 12
  threshold: 0.04
  window_size: 51
  smoothing_window_size: 11
  face_max_frame: 10
  min_face_size: 32
  max_face_distance_thr: 50
  method: "no_overlap+smoothing"
  align_margin: 0.3
  save_scenes: false
